export const catalogsKeys = {
  countries: ['catalogs', 'countries'] as const,
  states: ['catalogs', 'states'] as const,
  statesByCountry: (countryId: number) =>
    ['catalogs', 'states', { countryId }] as const,
  cities: ['catalogs', 'cities'] as const,
  citiesByState: (stateId: number) =>
    ['catalogs', 'cities', { stateId }] as const,
  civilStatuses: ['catalogs', 'civil-statuses'] as const,
  races: ['catalogs', 'races'] as const,
  socioeconomicLevels: ['catalogs', 'socioeconomic-levels'] as const,
  languages: ['catalogs', 'languages'] as const,
  bodySystems: ['catalogs', 'body-systems'] as const,
  paraclinicalCategories: ['catalogs', 'paraclinical-categories'] as const,
  medicationPresentations: ['catalogs', 'medication-presentations'] as const,
  medicationCategories: ['catalogs', 'medication-categories'] as const,
  medicalSpecialties: ['catalogs', 'medical-specialties'] as const,
  medications: ['catalogs', 'medications'] as const,
  paraclinicals: ['catalogs', 'paraclinicals'] as const,
  symptoms: ['catalogs', 'symptoms'] as const,
  allergyTypes: ['catalogs', 'allergy-types'] as const,
  allergySeverities: ['catalogs', 'allergy-severities'] as const,
  symptomSeverities: ['catalogs', 'symptom-severities'] as const,
  allergies: ['catalogs', 'allergies'] as const,
  diseases: ['catalogs', 'diseases'] as const,
  antecedentFamily: ['catalogs', 'antecedent-family'] as const,
  antecedentPersonal: ['catalogs', 'antecedent-personal'] as const,
  surgeries: ['catalogs', 'surgeries'] as const,
  hospitalizationReasons: ['catalogs', 'hospitalization-reasons'] as const,
}
