export const catalogsKeys = {
  countries: ['catalogs', 'countries'] as const,
  civilStatuses: ['catalogs', 'civil-statuses'] as const,
  races: ['catalogs', 'races'] as const,
  socioeconomicLevels: ['catalogs', 'socioeconomic-levels'] as const,
  languages: ['catalogs', 'languages'] as const,
  bodySystems: ['catalogs', 'body-systems'] as const,
  paraclinicalCategories: ['catalogs', 'paraclinical-categories'] as const,
  medicationPresentations: ['catalogs', 'medication-presentations'] as const,
  medicationCategories: ['catalogs', 'medication-categories'] as const,
  medicalSpecialties: ['catalogs', 'medical-specialties'] as const,
  medications: ['catalogs', 'medications'] as const,
  paraclinicals: ['catalogs', 'paraclinicals'] as const,
  symptoms: ['catalogs', 'symptoms'] as const,
}
