/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsuariosYRolesRouteImport } from './routes/_app/usuarios-y-roles'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppCuestionariosRouteImport } from './routes/_app/cuestionarios'
import { Route as AppCatalogosRouteImport } from './routes/_app/catalogos'
import { Route as AppCuestionariosIdRouteImport } from './routes/_app/cuestionarios.$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUsuariosYRolesRoute = AppUsuariosYRolesRouteImport.update({
  id: '/usuarios-y-roles',
  path: '/usuarios-y-roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCuestionariosRoute = AppCuestionariosRouteImport.update({
  id: '/cuestionarios',
  path: '/cuestionarios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatalogosRoute = AppCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCuestionariosIdRoute = AppCuestionariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCuestionariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/catalogos': typeof AppCatalogosRoute
  '/cuestionarios': typeof AppCuestionariosRouteWithChildren
  '/pacientes': typeof AppPacientesRoute
  '/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/login': typeof AuthLoginRoute
  '/cuestionarios/$id': typeof AppCuestionariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/catalogos': typeof AppCatalogosRoute
  '/cuestionarios': typeof AppCuestionariosRouteWithChildren
  '/pacientes': typeof AppPacientesRoute
  '/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/login': typeof AuthLoginRoute
  '/cuestionarios/$id': typeof AppCuestionariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/catalogos': typeof AppCatalogosRoute
  '/_app/cuestionarios': typeof AppCuestionariosRouteWithChildren
  '/_app/pacientes': typeof AppPacientesRoute
  '/_app/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cuestionarios/$id': typeof AppCuestionariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogos'
    | '/cuestionarios'
    | '/pacientes'
    | '/usuarios-y-roles'
    | '/login'
    | '/cuestionarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogos'
    | '/cuestionarios'
    | '/pacientes'
    | '/usuarios-y-roles'
    | '/login'
    | '/cuestionarios/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/catalogos'
    | '/_app/cuestionarios'
    | '/_app/pacientes'
    | '/_app/usuarios-y-roles'
    | '/_auth/login'
    | '/_app/'
    | '/_app/cuestionarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/usuarios-y-roles': {
      id: '/_app/usuarios-y-roles'
      path: '/usuarios-y-roles'
      fullPath: '/usuarios-y-roles'
      preLoaderRoute: typeof AppUsuariosYRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cuestionarios': {
      id: '/_app/cuestionarios'
      path: '/cuestionarios'
      fullPath: '/cuestionarios'
      preLoaderRoute: typeof AppCuestionariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/catalogos': {
      id: '/_app/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof AppCatalogosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cuestionarios/$id': {
      id: '/_app/cuestionarios/$id'
      path: '/$id'
      fullPath: '/cuestionarios/$id'
      preLoaderRoute: typeof AppCuestionariosIdRouteImport
      parentRoute: typeof AppCuestionariosRoute
    }
  }
}

interface AppCuestionariosRouteChildren {
  AppCuestionariosIdRoute: typeof AppCuestionariosIdRoute
}

const AppCuestionariosRouteChildren: AppCuestionariosRouteChildren = {
  AppCuestionariosIdRoute: AppCuestionariosIdRoute,
}

const AppCuestionariosRouteWithChildren =
  AppCuestionariosRoute._addFileChildren(AppCuestionariosRouteChildren)

interface AppRouteRouteChildren {
  AppCatalogosRoute: typeof AppCatalogosRoute
  AppCuestionariosRoute: typeof AppCuestionariosRouteWithChildren
  AppPacientesRoute: typeof AppPacientesRoute
  AppUsuariosYRolesRoute: typeof AppUsuariosYRolesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCatalogosRoute: AppCatalogosRoute,
  AppCuestionariosRoute: AppCuestionariosRouteWithChildren,
  AppPacientesRoute: AppPacientesRoute,
  AppUsuariosYRolesRoute: AppUsuariosYRolesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
