/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsuariosYRolesRouteImport } from './routes/_app/usuarios-y-roles'
import { Route as AppPacientesRouteImport } from './routes/_app/pacientes'
import { Route as AppIngresablesRouteImport } from './routes/_app/ingresables'
import { Route as AppEspecialistasRouteImport } from './routes/_app/especialistas'
import { Route as AppCitasRouteImport } from './routes/_app/citas'
import { Route as AppCatalogosRouteImport } from './routes/_app/catalogos'
import { Route as AppIngresablesIdRouteImport } from './routes/_app/ingresables_.$id'
import { Route as AppEspecialistasNuevoRouteImport } from './routes/_app/especialistas_.nuevo'
import { Route as AppEspecialistasSpecialistIdRouteImport } from './routes/_app/especialistas_.$specialistId'
import { Route as AppConsultasConsultationIdRouteImport } from './routes/_app/consultas_.$consultationId'
import { Route as AppPacientesPatientIdRouteRouteImport } from './routes/_app/pacientes_.$patientId/route'
import { Route as AppPacientesPatientIdIndexRouteImport } from './routes/_app/pacientes_.$patientId/index'
import { Route as AppPacientesPatientIdSintomasRouteImport } from './routes/_app/pacientes_.$patientId/sintomas'
import { Route as AppPacientesPatientIdResumenRouteImport } from './routes/_app/pacientes_.$patientId/resumen'
import { Route as AppPacientesPatientIdParaclinicosRouteImport } from './routes/_app/pacientes_.$patientId/paraclinicos'
import { Route as AppPacientesPatientIdMedicamentosRouteImport } from './routes/_app/pacientes_.$patientId/medicamentos'
import { Route as AppPacientesPatientIdIngresablesRouteImport } from './routes/_app/pacientes_.$patientId/ingresables'
import { Route as AppPacientesPatientIdExamenFisicoRouteImport } from './routes/_app/pacientes_.$patientId/examen-fisico'
import { Route as AppPacientesPatientIdEstiloDeVidaRouteImport } from './routes/_app/pacientes_.$patientId/estilo-de-vida'
import { Route as AppPacientesPatientIdEntregablesRouteImport } from './routes/_app/pacientes_.$patientId/entregables'
import { Route as AppPacientesPatientIdEnfermedadesRouteImport } from './routes/_app/pacientes_.$patientId/enfermedades'
import { Route as AppPacientesPatientIdConsultasRouteImport } from './routes/_app/pacientes_.$patientId/consultas'
import { Route as AppPacientesPatientIdComposicionCorporalRouteImport } from './routes/_app/pacientes_.$patientId/composicion-corporal'
import { Route as AppPacientesPatientIdAntecedentesRouteImport } from './routes/_app/pacientes_.$patientId/antecedentes'
import { Route as AppEspecialistasSpecialistIdEditarRouteImport } from './routes/_app/especialistas_.$specialistId_.editar'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUsuariosYRolesRoute = AppUsuariosYRolesRouteImport.update({
  id: '/usuarios-y-roles',
  path: '/usuarios-y-roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIngresablesRoute = AppIngresablesRouteImport.update({
  id: '/ingresables',
  path: '/ingresables',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEspecialistasRoute = AppEspecialistasRouteImport.update({
  id: '/especialistas',
  path: '/especialistas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCitasRoute = AppCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatalogosRoute = AppCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIngresablesIdRoute = AppIngresablesIdRouteImport.update({
  id: '/ingresables_/$id',
  path: '/ingresables/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEspecialistasNuevoRoute = AppEspecialistasNuevoRouteImport.update({
  id: '/especialistas_/nuevo',
  path: '/especialistas/nuevo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEspecialistasSpecialistIdRoute =
  AppEspecialistasSpecialistIdRouteImport.update({
    id: '/especialistas_/$specialistId',
    path: '/especialistas/$specialistId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConsultasConsultationIdRoute =
  AppConsultasConsultationIdRouteImport.update({
    id: '/consultas_/$consultationId',
    path: '/consultas/$consultationId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPacientesPatientIdRouteRoute =
  AppPacientesPatientIdRouteRouteImport.update({
    id: '/pacientes_/$patientId',
    path: '/pacientes/$patientId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPacientesPatientIdIndexRoute =
  AppPacientesPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdSintomasRoute =
  AppPacientesPatientIdSintomasRouteImport.update({
    id: '/sintomas',
    path: '/sintomas',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdResumenRoute =
  AppPacientesPatientIdResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdParaclinicosRoute =
  AppPacientesPatientIdParaclinicosRouteImport.update({
    id: '/paraclinicos',
    path: '/paraclinicos',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdMedicamentosRoute =
  AppPacientesPatientIdMedicamentosRouteImport.update({
    id: '/medicamentos',
    path: '/medicamentos',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdIngresablesRoute =
  AppPacientesPatientIdIngresablesRouteImport.update({
    id: '/ingresables',
    path: '/ingresables',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdExamenFisicoRoute =
  AppPacientesPatientIdExamenFisicoRouteImport.update({
    id: '/examen-fisico',
    path: '/examen-fisico',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdEstiloDeVidaRoute =
  AppPacientesPatientIdEstiloDeVidaRouteImport.update({
    id: '/estilo-de-vida',
    path: '/estilo-de-vida',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdEntregablesRoute =
  AppPacientesPatientIdEntregablesRouteImport.update({
    id: '/entregables',
    path: '/entregables',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdEnfermedadesRoute =
  AppPacientesPatientIdEnfermedadesRouteImport.update({
    id: '/enfermedades',
    path: '/enfermedades',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdConsultasRoute =
  AppPacientesPatientIdConsultasRouteImport.update({
    id: '/consultas',
    path: '/consultas',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdComposicionCorporalRoute =
  AppPacientesPatientIdComposicionCorporalRouteImport.update({
    id: '/composicion-corporal',
    path: '/composicion-corporal',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppPacientesPatientIdAntecedentesRoute =
  AppPacientesPatientIdAntecedentesRouteImport.update({
    id: '/antecedentes',
    path: '/antecedentes',
    getParentRoute: () => AppPacientesPatientIdRouteRoute,
  } as any)
const AppEspecialistasSpecialistIdEditarRoute =
  AppEspecialistasSpecialistIdEditarRouteImport.update({
    id: '/especialistas_/$specialistId_/editar',
    path: '/especialistas/$specialistId/editar',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/catalogos': typeof AppCatalogosRoute
  '/citas': typeof AppCitasRoute
  '/especialistas': typeof AppEspecialistasRoute
  '/ingresables': typeof AppIngresablesRoute
  '/pacientes': typeof AppPacientesRoute
  '/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/login': typeof AuthLoginRoute
  '/pacientes/$patientId': typeof AppPacientesPatientIdRouteRouteWithChildren
  '/consultas/$consultationId': typeof AppConsultasConsultationIdRoute
  '/especialistas/$specialistId': typeof AppEspecialistasSpecialistIdRoute
  '/especialistas/nuevo': typeof AppEspecialistasNuevoRoute
  '/ingresables/$id': typeof AppIngresablesIdRoute
  '/especialistas/$specialistId/editar': typeof AppEspecialistasSpecialistIdEditarRoute
  '/pacientes/$patientId/antecedentes': typeof AppPacientesPatientIdAntecedentesRoute
  '/pacientes/$patientId/composicion-corporal': typeof AppPacientesPatientIdComposicionCorporalRoute
  '/pacientes/$patientId/consultas': typeof AppPacientesPatientIdConsultasRoute
  '/pacientes/$patientId/enfermedades': typeof AppPacientesPatientIdEnfermedadesRoute
  '/pacientes/$patientId/entregables': typeof AppPacientesPatientIdEntregablesRoute
  '/pacientes/$patientId/estilo-de-vida': typeof AppPacientesPatientIdEstiloDeVidaRoute
  '/pacientes/$patientId/examen-fisico': typeof AppPacientesPatientIdExamenFisicoRoute
  '/pacientes/$patientId/ingresables': typeof AppPacientesPatientIdIngresablesRoute
  '/pacientes/$patientId/medicamentos': typeof AppPacientesPatientIdMedicamentosRoute
  '/pacientes/$patientId/paraclinicos': typeof AppPacientesPatientIdParaclinicosRoute
  '/pacientes/$patientId/resumen': typeof AppPacientesPatientIdResumenRoute
  '/pacientes/$patientId/sintomas': typeof AppPacientesPatientIdSintomasRoute
  '/pacientes/$patientId/': typeof AppPacientesPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/catalogos': typeof AppCatalogosRoute
  '/citas': typeof AppCitasRoute
  '/especialistas': typeof AppEspecialistasRoute
  '/ingresables': typeof AppIngresablesRoute
  '/pacientes': typeof AppPacientesRoute
  '/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/login': typeof AuthLoginRoute
  '/consultas/$consultationId': typeof AppConsultasConsultationIdRoute
  '/especialistas/$specialistId': typeof AppEspecialistasSpecialistIdRoute
  '/especialistas/nuevo': typeof AppEspecialistasNuevoRoute
  '/ingresables/$id': typeof AppIngresablesIdRoute
  '/especialistas/$specialistId/editar': typeof AppEspecialistasSpecialistIdEditarRoute
  '/pacientes/$patientId/antecedentes': typeof AppPacientesPatientIdAntecedentesRoute
  '/pacientes/$patientId/composicion-corporal': typeof AppPacientesPatientIdComposicionCorporalRoute
  '/pacientes/$patientId/consultas': typeof AppPacientesPatientIdConsultasRoute
  '/pacientes/$patientId/enfermedades': typeof AppPacientesPatientIdEnfermedadesRoute
  '/pacientes/$patientId/entregables': typeof AppPacientesPatientIdEntregablesRoute
  '/pacientes/$patientId/estilo-de-vida': typeof AppPacientesPatientIdEstiloDeVidaRoute
  '/pacientes/$patientId/examen-fisico': typeof AppPacientesPatientIdExamenFisicoRoute
  '/pacientes/$patientId/ingresables': typeof AppPacientesPatientIdIngresablesRoute
  '/pacientes/$patientId/medicamentos': typeof AppPacientesPatientIdMedicamentosRoute
  '/pacientes/$patientId/paraclinicos': typeof AppPacientesPatientIdParaclinicosRoute
  '/pacientes/$patientId/resumen': typeof AppPacientesPatientIdResumenRoute
  '/pacientes/$patientId/sintomas': typeof AppPacientesPatientIdSintomasRoute
  '/pacientes/$patientId': typeof AppPacientesPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/catalogos': typeof AppCatalogosRoute
  '/_app/citas': typeof AppCitasRoute
  '/_app/especialistas': typeof AppEspecialistasRoute
  '/_app/ingresables': typeof AppIngresablesRoute
  '/_app/pacientes': typeof AppPacientesRoute
  '/_app/usuarios-y-roles': typeof AppUsuariosYRolesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pacientes_/$patientId': typeof AppPacientesPatientIdRouteRouteWithChildren
  '/_app/consultas_/$consultationId': typeof AppConsultasConsultationIdRoute
  '/_app/especialistas_/$specialistId': typeof AppEspecialistasSpecialistIdRoute
  '/_app/especialistas_/nuevo': typeof AppEspecialistasNuevoRoute
  '/_app/ingresables_/$id': typeof AppIngresablesIdRoute
  '/_app/especialistas_/$specialistId_/editar': typeof AppEspecialistasSpecialistIdEditarRoute
  '/_app/pacientes_/$patientId/antecedentes': typeof AppPacientesPatientIdAntecedentesRoute
  '/_app/pacientes_/$patientId/composicion-corporal': typeof AppPacientesPatientIdComposicionCorporalRoute
  '/_app/pacientes_/$patientId/consultas': typeof AppPacientesPatientIdConsultasRoute
  '/_app/pacientes_/$patientId/enfermedades': typeof AppPacientesPatientIdEnfermedadesRoute
  '/_app/pacientes_/$patientId/entregables': typeof AppPacientesPatientIdEntregablesRoute
  '/_app/pacientes_/$patientId/estilo-de-vida': typeof AppPacientesPatientIdEstiloDeVidaRoute
  '/_app/pacientes_/$patientId/examen-fisico': typeof AppPacientesPatientIdExamenFisicoRoute
  '/_app/pacientes_/$patientId/ingresables': typeof AppPacientesPatientIdIngresablesRoute
  '/_app/pacientes_/$patientId/medicamentos': typeof AppPacientesPatientIdMedicamentosRoute
  '/_app/pacientes_/$patientId/paraclinicos': typeof AppPacientesPatientIdParaclinicosRoute
  '/_app/pacientes_/$patientId/resumen': typeof AppPacientesPatientIdResumenRoute
  '/_app/pacientes_/$patientId/sintomas': typeof AppPacientesPatientIdSintomasRoute
  '/_app/pacientes_/$patientId/': typeof AppPacientesPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogos'
    | '/citas'
    | '/especialistas'
    | '/ingresables'
    | '/pacientes'
    | '/usuarios-y-roles'
    | '/login'
    | '/pacientes/$patientId'
    | '/consultas/$consultationId'
    | '/especialistas/$specialistId'
    | '/especialistas/nuevo'
    | '/ingresables/$id'
    | '/especialistas/$specialistId/editar'
    | '/pacientes/$patientId/antecedentes'
    | '/pacientes/$patientId/composicion-corporal'
    | '/pacientes/$patientId/consultas'
    | '/pacientes/$patientId/enfermedades'
    | '/pacientes/$patientId/entregables'
    | '/pacientes/$patientId/estilo-de-vida'
    | '/pacientes/$patientId/examen-fisico'
    | '/pacientes/$patientId/ingresables'
    | '/pacientes/$patientId/medicamentos'
    | '/pacientes/$patientId/paraclinicos'
    | '/pacientes/$patientId/resumen'
    | '/pacientes/$patientId/sintomas'
    | '/pacientes/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogos'
    | '/citas'
    | '/especialistas'
    | '/ingresables'
    | '/pacientes'
    | '/usuarios-y-roles'
    | '/login'
    | '/consultas/$consultationId'
    | '/especialistas/$specialistId'
    | '/especialistas/nuevo'
    | '/ingresables/$id'
    | '/especialistas/$specialistId/editar'
    | '/pacientes/$patientId/antecedentes'
    | '/pacientes/$patientId/composicion-corporal'
    | '/pacientes/$patientId/consultas'
    | '/pacientes/$patientId/enfermedades'
    | '/pacientes/$patientId/entregables'
    | '/pacientes/$patientId/estilo-de-vida'
    | '/pacientes/$patientId/examen-fisico'
    | '/pacientes/$patientId/ingresables'
    | '/pacientes/$patientId/medicamentos'
    | '/pacientes/$patientId/paraclinicos'
    | '/pacientes/$patientId/resumen'
    | '/pacientes/$patientId/sintomas'
    | '/pacientes/$patientId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/catalogos'
    | '/_app/citas'
    | '/_app/especialistas'
    | '/_app/ingresables'
    | '/_app/pacientes'
    | '/_app/usuarios-y-roles'
    | '/_auth/login'
    | '/_app/'
    | '/_app/pacientes_/$patientId'
    | '/_app/consultas_/$consultationId'
    | '/_app/especialistas_/$specialistId'
    | '/_app/especialistas_/nuevo'
    | '/_app/ingresables_/$id'
    | '/_app/especialistas_/$specialistId_/editar'
    | '/_app/pacientes_/$patientId/antecedentes'
    | '/_app/pacientes_/$patientId/composicion-corporal'
    | '/_app/pacientes_/$patientId/consultas'
    | '/_app/pacientes_/$patientId/enfermedades'
    | '/_app/pacientes_/$patientId/entregables'
    | '/_app/pacientes_/$patientId/estilo-de-vida'
    | '/_app/pacientes_/$patientId/examen-fisico'
    | '/_app/pacientes_/$patientId/ingresables'
    | '/_app/pacientes_/$patientId/medicamentos'
    | '/_app/pacientes_/$patientId/paraclinicos'
    | '/_app/pacientes_/$patientId/resumen'
    | '/_app/pacientes_/$patientId/sintomas'
    | '/_app/pacientes_/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/usuarios-y-roles': {
      id: '/_app/usuarios-y-roles'
      path: '/usuarios-y-roles'
      fullPath: '/usuarios-y-roles'
      preLoaderRoute: typeof AppUsuariosYRolesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ingresables': {
      id: '/_app/ingresables'
      path: '/ingresables'
      fullPath: '/ingresables'
      preLoaderRoute: typeof AppIngresablesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/especialistas': {
      id: '/_app/especialistas'
      path: '/especialistas'
      fullPath: '/especialistas'
      preLoaderRoute: typeof AppEspecialistasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/citas': {
      id: '/_app/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AppCitasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/catalogos': {
      id: '/_app/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof AppCatalogosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ingresables_/$id': {
      id: '/_app/ingresables_/$id'
      path: '/ingresables/$id'
      fullPath: '/ingresables/$id'
      preLoaderRoute: typeof AppIngresablesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/especialistas_/nuevo': {
      id: '/_app/especialistas_/nuevo'
      path: '/especialistas/nuevo'
      fullPath: '/especialistas/nuevo'
      preLoaderRoute: typeof AppEspecialistasNuevoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/especialistas_/$specialistId': {
      id: '/_app/especialistas_/$specialistId'
      path: '/especialistas/$specialistId'
      fullPath: '/especialistas/$specialistId'
      preLoaderRoute: typeof AppEspecialistasSpecialistIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/consultas_/$consultationId': {
      id: '/_app/consultas_/$consultationId'
      path: '/consultas/$consultationId'
      fullPath: '/consultas/$consultationId'
      preLoaderRoute: typeof AppConsultasConsultationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pacientes_/$patientId': {
      id: '/_app/pacientes_/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof AppPacientesPatientIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pacientes_/$patientId/': {
      id: '/_app/pacientes_/$patientId/'
      path: '/'
      fullPath: '/pacientes/$patientId/'
      preLoaderRoute: typeof AppPacientesPatientIdIndexRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/sintomas': {
      id: '/_app/pacientes_/$patientId/sintomas'
      path: '/sintomas'
      fullPath: '/pacientes/$patientId/sintomas'
      preLoaderRoute: typeof AppPacientesPatientIdSintomasRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/resumen': {
      id: '/_app/pacientes_/$patientId/resumen'
      path: '/resumen'
      fullPath: '/pacientes/$patientId/resumen'
      preLoaderRoute: typeof AppPacientesPatientIdResumenRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/paraclinicos': {
      id: '/_app/pacientes_/$patientId/paraclinicos'
      path: '/paraclinicos'
      fullPath: '/pacientes/$patientId/paraclinicos'
      preLoaderRoute: typeof AppPacientesPatientIdParaclinicosRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/medicamentos': {
      id: '/_app/pacientes_/$patientId/medicamentos'
      path: '/medicamentos'
      fullPath: '/pacientes/$patientId/medicamentos'
      preLoaderRoute: typeof AppPacientesPatientIdMedicamentosRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/ingresables': {
      id: '/_app/pacientes_/$patientId/ingresables'
      path: '/ingresables'
      fullPath: '/pacientes/$patientId/ingresables'
      preLoaderRoute: typeof AppPacientesPatientIdIngresablesRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/examen-fisico': {
      id: '/_app/pacientes_/$patientId/examen-fisico'
      path: '/examen-fisico'
      fullPath: '/pacientes/$patientId/examen-fisico'
      preLoaderRoute: typeof AppPacientesPatientIdExamenFisicoRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/estilo-de-vida': {
      id: '/_app/pacientes_/$patientId/estilo-de-vida'
      path: '/estilo-de-vida'
      fullPath: '/pacientes/$patientId/estilo-de-vida'
      preLoaderRoute: typeof AppPacientesPatientIdEstiloDeVidaRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/entregables': {
      id: '/_app/pacientes_/$patientId/entregables'
      path: '/entregables'
      fullPath: '/pacientes/$patientId/entregables'
      preLoaderRoute: typeof AppPacientesPatientIdEntregablesRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/enfermedades': {
      id: '/_app/pacientes_/$patientId/enfermedades'
      path: '/enfermedades'
      fullPath: '/pacientes/$patientId/enfermedades'
      preLoaderRoute: typeof AppPacientesPatientIdEnfermedadesRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/consultas': {
      id: '/_app/pacientes_/$patientId/consultas'
      path: '/consultas'
      fullPath: '/pacientes/$patientId/consultas'
      preLoaderRoute: typeof AppPacientesPatientIdConsultasRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/composicion-corporal': {
      id: '/_app/pacientes_/$patientId/composicion-corporal'
      path: '/composicion-corporal'
      fullPath: '/pacientes/$patientId/composicion-corporal'
      preLoaderRoute: typeof AppPacientesPatientIdComposicionCorporalRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/pacientes_/$patientId/antecedentes': {
      id: '/_app/pacientes_/$patientId/antecedentes'
      path: '/antecedentes'
      fullPath: '/pacientes/$patientId/antecedentes'
      preLoaderRoute: typeof AppPacientesPatientIdAntecedentesRouteImport
      parentRoute: typeof AppPacientesPatientIdRouteRoute
    }
    '/_app/especialistas_/$specialistId_/editar': {
      id: '/_app/especialistas_/$specialistId_/editar'
      path: '/especialistas/$specialistId/editar'
      fullPath: '/especialistas/$specialistId/editar'
      preLoaderRoute: typeof AppEspecialistasSpecialistIdEditarRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppPacientesPatientIdRouteRouteChildren {
  AppPacientesPatientIdAntecedentesRoute: typeof AppPacientesPatientIdAntecedentesRoute
  AppPacientesPatientIdComposicionCorporalRoute: typeof AppPacientesPatientIdComposicionCorporalRoute
  AppPacientesPatientIdConsultasRoute: typeof AppPacientesPatientIdConsultasRoute
  AppPacientesPatientIdEnfermedadesRoute: typeof AppPacientesPatientIdEnfermedadesRoute
  AppPacientesPatientIdEntregablesRoute: typeof AppPacientesPatientIdEntregablesRoute
  AppPacientesPatientIdEstiloDeVidaRoute: typeof AppPacientesPatientIdEstiloDeVidaRoute
  AppPacientesPatientIdExamenFisicoRoute: typeof AppPacientesPatientIdExamenFisicoRoute
  AppPacientesPatientIdIngresablesRoute: typeof AppPacientesPatientIdIngresablesRoute
  AppPacientesPatientIdMedicamentosRoute: typeof AppPacientesPatientIdMedicamentosRoute
  AppPacientesPatientIdParaclinicosRoute: typeof AppPacientesPatientIdParaclinicosRoute
  AppPacientesPatientIdResumenRoute: typeof AppPacientesPatientIdResumenRoute
  AppPacientesPatientIdSintomasRoute: typeof AppPacientesPatientIdSintomasRoute
  AppPacientesPatientIdIndexRoute: typeof AppPacientesPatientIdIndexRoute
}

const AppPacientesPatientIdRouteRouteChildren: AppPacientesPatientIdRouteRouteChildren =
  {
    AppPacientesPatientIdAntecedentesRoute:
      AppPacientesPatientIdAntecedentesRoute,
    AppPacientesPatientIdComposicionCorporalRoute:
      AppPacientesPatientIdComposicionCorporalRoute,
    AppPacientesPatientIdConsultasRoute: AppPacientesPatientIdConsultasRoute,
    AppPacientesPatientIdEnfermedadesRoute:
      AppPacientesPatientIdEnfermedadesRoute,
    AppPacientesPatientIdEntregablesRoute:
      AppPacientesPatientIdEntregablesRoute,
    AppPacientesPatientIdEstiloDeVidaRoute:
      AppPacientesPatientIdEstiloDeVidaRoute,
    AppPacientesPatientIdExamenFisicoRoute:
      AppPacientesPatientIdExamenFisicoRoute,
    AppPacientesPatientIdIngresablesRoute:
      AppPacientesPatientIdIngresablesRoute,
    AppPacientesPatientIdMedicamentosRoute:
      AppPacientesPatientIdMedicamentosRoute,
    AppPacientesPatientIdParaclinicosRoute:
      AppPacientesPatientIdParaclinicosRoute,
    AppPacientesPatientIdResumenRoute: AppPacientesPatientIdResumenRoute,
    AppPacientesPatientIdSintomasRoute: AppPacientesPatientIdSintomasRoute,
    AppPacientesPatientIdIndexRoute: AppPacientesPatientIdIndexRoute,
  }

const AppPacientesPatientIdRouteRouteWithChildren =
  AppPacientesPatientIdRouteRoute._addFileChildren(
    AppPacientesPatientIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppCatalogosRoute: typeof AppCatalogosRoute
  AppCitasRoute: typeof AppCitasRoute
  AppEspecialistasRoute: typeof AppEspecialistasRoute
  AppIngresablesRoute: typeof AppIngresablesRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppUsuariosYRolesRoute: typeof AppUsuariosYRolesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPacientesPatientIdRouteRoute: typeof AppPacientesPatientIdRouteRouteWithChildren
  AppConsultasConsultationIdRoute: typeof AppConsultasConsultationIdRoute
  AppEspecialistasSpecialistIdRoute: typeof AppEspecialistasSpecialistIdRoute
  AppEspecialistasNuevoRoute: typeof AppEspecialistasNuevoRoute
  AppIngresablesIdRoute: typeof AppIngresablesIdRoute
  AppEspecialistasSpecialistIdEditarRoute: typeof AppEspecialistasSpecialistIdEditarRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCatalogosRoute: AppCatalogosRoute,
  AppCitasRoute: AppCitasRoute,
  AppEspecialistasRoute: AppEspecialistasRoute,
  AppIngresablesRoute: AppIngresablesRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppUsuariosYRolesRoute: AppUsuariosYRolesRoute,
  AppIndexRoute: AppIndexRoute,
  AppPacientesPatientIdRouteRoute: AppPacientesPatientIdRouteRouteWithChildren,
  AppConsultasConsultationIdRoute: AppConsultasConsultationIdRoute,
  AppEspecialistasSpecialistIdRoute: AppEspecialistasSpecialistIdRoute,
  AppEspecialistasNuevoRoute: AppEspecialistasNuevoRoute,
  AppIngresablesIdRoute: AppIngresablesIdRoute,
  AppEspecialistasSpecialistIdEditarRoute:
    AppEspecialistasSpecialistIdEditarRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
